python measure-sequoia.py --update-database \
&& python measure-sequoia.py --update-database \
&& python measure-sequoia.py --update-database \
&& python measure-sequoia.py --update-database \
&& python measure-sequoia.py --update-database \
&& python measure-sequoia.py --update-database \
&& python measure-sequoia.py --update-database \
&& python measure-sequoia.py --update-database \
&& python measure-sequoia.py --update-database \
&& python measure-sequoia.py --update-database \
&& python measure-sequoia.py --update-database \
&& python measure-sequoia.py --update-database \
&& python measure-sequoia.py --update-database \
&& python measure-sequoia.py --update-database \
&& python measure-sequoia.py --update-database \
&& python measure-sequoia.py --update-database \
&& python measure-sequoia.py --update-database \
&& python measure-sequoia.py --update-database \
&& python measure-sequoia.py --update-database \
&& python measure-sequoia.py --update-database \
&& python measure-sequoia.py --update-database \
&& python measure-sequoia.py --update-database \
&& python measure-sequoia.py --update-database \
&& python measure-sequoia.py --update-database \
&& python measure-sequoia.py --update-database \
&& python measure-sequoia.py --update-database \
&& python measure-sequoia.py --update-database \
&& python measure-sequoia.py --update-database \
&& python measure-sequoia.py --update-database \
&& python measure-sequoia.py --update-database \
&& python measure-sequoia.py --update-database \
&& python measure-sequoia.py --update-database \
&& python measure-sequoia.py --update-database \
&& python measure-sequoia.py --update-database \
&& python measure-sequoia.py --update-database \
&& python measure-sequoia.py --update-database \
&& python measure-sequoia.py --update-database \
&& python measure-sequoia.py --update-database \
&& python measure-sequoia.py --update-database \
&& python measure-sequoia.py --update-database \
