bokeh html -o diagrams/clique.html bars.py --args -f clique
bokeh html -o diagrams/connected.html bars.py --args -f connected
bokeh html -o diagrams/3col2.html bars.py --args -f 3col2
bokeh html -o diagrams/d2-dominating-set.html bars.py --args -f d2-dominating-set
bokeh html -o diagrams/dominating-set.html bars.py --args -f dominating-set
bokeh html -o diagrams/longest-cycle.html bars.py --args -f longest-cycle
bokeh html -o diagrams/hamiltonian-cycle.html bars.py --args -f hamiltonian-cycle
bokeh html -o diagrams/connected-domset.html bars.py --args -f connected-domset
bokeh html -o diagrams/3col.html bars.py --args -f 3col
bokeh html -o diagrams/independent-set.html bars.py --args -f independent-set
bokeh html -o diagrams/3col-free2.html bars.py --args -f 3col-free2
bokeh html -o diagrams/vertex-cover.html bars.py --args -f vertex-cover
bokeh html -o diagrams/steiner.html bars.py --args -f steiner
bokeh html -o diagrams/d3-dominating-set.html bars.py --args -f d3-dominating-set
bokeh html -o diagrams/bipartite.html bars.py --args -f bipartite
bokeh html -o diagrams/3col-free.html bars.py --args -f 3col-free
